### ISSUE TITLE
Feature request: Convert HYDRAD output to single H5 file

### ISSUE THREAD

**Issue by jwreep** [rice-solar-physics/pydrad#115]
That is, take some permutation of .phy, .hstate, .ine, etc. files over some time range and convert it to a single H5 file.  This would make sharing results significantly easier if we could deliver a single file.  

This is also a lot easier to do in Python instead of writing a C-module.

What do you think?

**Comment by wtbarnes** [comment]
Yes, I think this is a really good idea! I think this is sort of what I had in mind in #96? But maybe it needn't be that complicated. Actually, I think I have a good idea for what this would look like. I'm going to open a PR with a prototype before I forget 😅

**Comment by jwreep** [comment]
Oops, missed that issue before making this post.  Yes, same idea, though.

**Comment by wtbarnes** [comment]
Should these be interpolated onto a uniform grid with each variable stored as a time-distance array? Or should each timestep be it its own dataset?

**Comment by sjbradshaw** [comment]
All the file output is done in CAdaptiveMesh::WriteToFile() in mesh.cpp, so this function can be modified (or another one written and overloaded) to write the new format. I’ve been thinking about this for a while to reduce redundancy and also to label the data so that people know what the quantities, units, etc., are.

 

Cheers,

 

Steve

**Comment by jwreep** [comment]
I would say that this should be to deliver the raw data, so do it without interpolation.  The rest of the pydrad code could still interpolate afterwards, no?

**Comment by jwreep** [comment]
I also agree with Steve that appending the units on the data would make things much clearer, particularly for new users of HYDRAD.
