### ISSUE TITLE
Make sample config dict more visible

### ISSUE THREAD

**Issue by jwreep** [rice-solar-physics/pydrad#138]
It would be extremely useful to have a sample configuration `dict` bundled in the repository, perhaps with recommended defaults.  It's a bit tedious to set one up from scratch.

**Comment by wtbarnes** [comment]
Check https://github.com/rice-solar-physics/pydrad/blob/master/defaults.asdf. You can then load it like so: https://pydrad.readthedocs.io/en/latest/configure.html#setting-a-default-configuration. Note that you can also save out your own config and read it back in at any time: https://pydrad.readthedocs.io/en/latest/api/pydrad.configure.Configure.html#pydrad.configure.Configure.save_config

**Comment by jwreep** [comment]
Ah, thanks.  I missed this.

**Comment by wtbarnes** [comment]
Though I think it is fair to say we should make this more visible and maybe easier to access from the package.

**Comment by jwreep** [comment]
Is there a function to print out the whole thing?  What I'm imagining is just quickly configuring a jupyter notebook, which can be done quickest if one can see all of the possible entries at once.  For example, just copying and pasting a complete dictionary to the top of this page: https://rice-solar-physics.github.io/pydrad/configure/
