### ISSUE TITLE
Function for calculating thermodynamic variables from conserved variables

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/pydrad#86]
In effect, this would create what's currently in the `.phy` files from the quantities in the `.amr` files.

**Comment by wtbarnes** [comment]
A follow-up question: how exactly do we handle the case where we have separate electron and ion mass densities? It is easy enough to adjust the index appropriately to make sure we are parsing the right column. But then how do we compute the velocity from the momentum density? Would it just be the average of the electron and ion mass densities divided by the momentum density?

**Comment by sjbradshaw** [comment]
Since m_e << m_i then computing the velocity from the momentum density is simply:

 

V = rho_V / ( m_i n_i )

 

The mass of the electron component of the fluid contributes negligibly to the momentum density.
