### ISSUE TITLE
Two new preprocessor directives added to HYDRAD

### ISSUE THREAD

**Issue by jwreep** [rice-solar-physics/pydrad#91]
#define USE_SINGLE_VALUE_DECOMPOSITION
#define USE_LOWER_UPPER_DECOMPOSITION

The two are mutually exclusive.  Only one can be defined.  This specifies which decomposition (SVD or LU) to use for the NLTE_CHROMOSPHERE.

**Comment by wtbarnes** [comment]
Thanks! Which file should these go into? `RadiationModel/source/config.h`? `HYDRAD/source/config.h`?

**Comment by jwreep** [comment]
They're actually in Radiation_Model/OpticallyThick/RadiativeRates.h

On second thought, maybe pydrad need not ever change these.  They're essentially specifying detailed numerics that the average user might not care about.

**Comment by wtbarnes** [comment]
If it's a possible input parameter, it's worth adding as another config option. It's easy enough to add a template for `RadiativeRates.h`. Is there any reason these options couldn't be in one of the more "standard" config header files?

**Comment by jwreep** [comment]
In principle they could be, but they're not used by any of the rest of the code and they probably shouldn't be modified unless you know what they do.

**Comment by sjbradshaw** [comment]
The SVD code will eventually be deprecated and removed. These two defines are only for internal purposes (testing, benchmarking, debugging). The end user will never see them and they will be removed with the SVD code.

**Comment by wtbarnes** [comment]
Alright then. Won't worry about it here!
